package selflearning.chemistree.domain.chemistry.inorganic.oxides

object Oxides {

    val oxides = sequenceOf(
        Oxide(
            "Cu2O",
            "copper_1_oxide",
            1,
            "amphoteric",
            2
        ),
        Oxide(
            "Cs2O",
            "caesium_oxide",
            1,
            "basic",
            2
        ),
        Oxide(
            "C2O",
            "dicarbon_monoxide",
            1,
            "non_salt_forming",
            3
        ),
        Oxide(
            "Cl2O",
            "dichlorine_monoxide",
            1,
            "acidic",
            2
        ),
        Oxide(
            "Ga2O",
            "gallium_1_oxide",
            1,
            "basic",
            2
        ),
        Oxide(
            "Li2O",
            "lithium_oxide",
            1,
            "basic",
            1
        ),
        Oxide(
            "K2O",
            "potassium_oxide",
            1,
            "basic",
            1
        ),
        Oxide(
            "Rb2O",
            "rubidium_oxide",
            1,
            "basic",
            2
        ),
        Oxide(
            "Ag2O",
            "silver_oxide",
            1,
            "basic",
            2
        ),
        Oxide(
            "Tl2O",
            "thallium_1_oxide",
            1,
            "basic",
            3
        ),
        Oxide(
            "Na2O",
            "sodium_oxide",
            1,
            "basic",
            1
        ),
        Oxide(
            "H2O",
            "hydrogen_oxide",
            1,
            "non_salt_forming",
            1
        ),
        Oxide(
            "BaO",
            "barium_oxide",
            2,
            "basic",
            1
        ),
        Oxide(
            "BeO",
            "beryllium_oxide",
            2,
            "amphoteric",
            1
        ),
        Oxide(
            "CdO",
            "cadmium_oxide",
            2,
            "basic",
            3
        ),
        Oxide(
            "CaO",
            "calcium_oxide",
            2,
            "basic",
            1
        ),
        Oxide(
            "CO",
            "carbon_monoxide",
            2,
            "non_salt_forming",
            1
        ),
        Oxide(
            "CrO",
            "chromium_2_oxide",
            2,
            "basic",
            2
        ),
        Oxide(
            "CoO",
            "cobalt_2_oxide",
            2,
            "basic",
            3
        ),
        Oxide(
            "CuO",
            "copper_2_oxide",
            2,
            "amphoteric",
            1
        ),
        Oxide(
            "GeO",
            "germanium_monoxide",
            2,
            "basic",
            3
        ),
        Oxide(
            "FeO",
            "iron_2_oxide",
            2,
            "basic",
            1
        ),
        Oxide(
            "PbO",
            "lead_2_oxide",
            2,
            "amphoteric",
            1
        ),
        Oxide(
            "MgO",
            "magnesium_oxide",
            2,
            "basic",
            1
        ),
        Oxide(
            "MnO",
            "manganese_2_oxide",
            2,
            "basic",
            2
        ),
        Oxide(
            "HgO",
            "mercury_2_oxide",
            2,
            "basic",
            2
        ),
        Oxide(
            "NiO",
            "nickel_2_oxide",
            2,
            "amphoteric",
            2
        ),
        Oxide(
            "NO",
            "nitric_oxide",
            2,
            "non_salt_forming",
            1
        ),
        Oxide(
            "PdO",
            "palladium_2_oxide",
            2,
            "amphoteric",
            2
        ),
        Oxide(
            "SiO",
            "silicon_monoxide",
            2,
            "non_salt_forming",
            2
        ),
        Oxide(
            "SrO",
            "strontium_oxide",
            2,
            "basic",
            2
        ),
        Oxide(
            "SO",
            "sulfur_monoxide",
            2,
            "non_salt_forming",
            3
        ),
        Oxide(
            "S2O2",
            "disulfur_dioxide",
            2,
            "non_salt_forming",
            3
        ),
        Oxide(
            "SnO",
            "tin_2_oxide",
            2,
            "amphoteric",
            2
        ),
        Oxide(
            "TiO",
            "titanium_2_oxide",
            2,
            "basic",
            2
        ),
        Oxide(
            "VO",
            "vanadium_2_oxide",
            2,
            "basic",
            3
        ),
        Oxide(
            "ZnO",
            "zinc_oxide",
            2,
            "amphoteric",
            1
        ),
        Oxide(
            "Al2O3",
            "aluminium_oxide",
            3,
            "amphoteric",
            1
        ),
        Oxide(
            "Sb2O3",
            "antimony_trioxide",
            3,
            "amphoteric",
            3
        ),
        Oxide(
            "As2O3",
            "arsenic_trioxide",
            3,
            "amphoteric",
            2
        ),
        Oxide(
            "Bi2O3",
            "bismuth_3_oxide",
            3,
            "amphoteric",
            3
        ),
        Oxide(
            "B2O3",
            "boron_trioxide",
            3,
            "acidic",
            2
        ),
        Oxide(
            "Ce2O3",
            "cerium_3_oxide",
            3,
            "amphoteric",
            3
        ),
        Oxide(
            "Br2O3",
            "dibromine_trioxide",
            3,
            "acidic",
            2
        ),
        Oxide(
            "Cr2O3",
            "chromium_3_oxide",
            3,
            "amphoteric",
            2
        ),
        Oxide(
            "N2O3",
            "dinitrogen_trioxide",
            3,
            "acidic",
            1
        ),
        Oxide(
            "Eu2O3",
            "europium_3_oxide",
            3,
            "basic",
            3
        ),
        Oxide(
            "Ga2O3",
            "gallium_3_oxide",
            3,
            "amphoteric",
            3
        ),
        Oxide(
            "In2O3",
            "indium_3_oxide",
            3,
            "amphoteric",
            2
        ),
        Oxide(
            "Fe2O3",
            "iron_3_oxide",
            3,
            "amphoteric",
            1
        ),
        Oxide(
            "La2O3",
            "lanthanum_oxide",
            3,
            "basic",
            3
        ),
        Oxide(
            "Mn2O3",
            "manganese_3_oxide",
            3,
            "amphoteric",
            2
        ),
        Oxide(
            "P4O6",
            "phosphorus_trioxide",
            3,
            "acidic",
            1
        ),
        Oxide(
            "Pr2O3",
            "praseodymium_3_oxide",
            3,
            "basic",
            3
        ),
        Oxide(
            "Sm2O3",
            "samarium_3_oxide",
            3,
            "basic",
            3
        ),
        Oxide(
            "Sc2O3",
            "scandium_oxide",
            3,
            "amphoteric",
            3
        ),
        Oxide(
            "Tb2O3",
            "terbium_3_oxide",
            3,
            "basic",
            3
        ),
        Oxide(
            "Tl2O3",
            "thallium_3_oxide",
            3,
            "amphoteric",
            3
        ),
        Oxide(
            "V2O3",
            "vanadium_3_oxide",
            3,
            "basic",
            3
        ),
        Oxide(
            "Y2O3",
            "yttrium_3_oxide",
            3,
            "basic",
            3
        ),
        Oxide(
            "CO2",
            "carbon_dioxide",
            4,
            "acidic",
            1
        ),
        Oxide(
            "ClO2",
            "chlorine_dioxide",
            4,
            "acidic",
            2
        ),
        Oxide(
            "CrO2",
            "chromium_4_oxide",
            4,
            "amphoteric",
            2
        ),
        Oxide(
            "N2O4",
            "dinitrogen_tetroxide",
            4,
            "acidic",
            2
        ),
        Oxide(
            "GeO2",
            "germanium_dioxide",
            4,
            "amphoteric",
            2
        ),
        Oxide(
            "HfO2",
            "hafnium_4_oxide",
            4,
            "amphoteric",
            3
        ),
        Oxide(
            "PbO2",
            "lead_dioxide",
            4,
            "amphoteric",
            2
        ),
        Oxide(
            "MnO2",
            "manganese_dioxide",
            4,
            "amphoteric",
            1
        ),
        Oxide(
            "NO2",
            "nitrogen_dioxide",
            4,
            "acidic",
            1
        ),
        Oxide(
            "RuO2",
            "ruthenium_4_oxide",
            4,
            "amphoteric",
            3
        ),
        Oxide(
            "SeO2",
            "selenium_dioxide",
            4,
            "acidic",
            2
        ),
        Oxide(
            "SiO2",
            "silicon_dioxide",
            4,
            "acidic",
            1
        ),
        Oxide(
            "SO2",
            "sulfur_dioxide",
            4,
            "acidic",
            1
        ),
        Oxide(
            "TeO2",
            "tellurium_dioxide",
            4,
            "amphoteric",
            3
        ),
        Oxide(
            "SnO2",
            "tin_dioxide",
            4,
            "amphoteric",
            3
        ),
        Oxide(
            "TiO2",
            "titanium_dioxide",
            4,
            "amphoteric",
            2
        ),
        Oxide(
            "WO2",
            "tungsten_4_oxide",
            4,
            "amphoteric",
            3
        ),
        Oxide(
            "VO2",
            "vanadium_4_oxide",
            4,
            "amphoteric",
            3
        ),
        Oxide(
            "ZrO2",
            "zirconium_dioxide",
            4,
            "amphoteric",
            3
        ),
        Oxide(
            "Sb2O5",
            "antimony_pentoxide",
            5,
            "acidic",
            3
        ),
        Oxide(
            "As2O5",
            "arsenic_pentoxide",
            5,
            "acidic",
            2
        ),
        Oxide(
            "N2O5",
            "dinitrogen_pentoxide",
            5,
            "acidic",
            1
        ),
        Oxide(
            "Nb2O5",
            "niobium_pentoxide",
            5,
            "acidic",
            3
        ),
        Oxide(
            "P2O5",
            "phosphorus_pentoxide",
            5,
            "acidic",
            1
        ),
        Oxide(
            "Ta2O5",
            "tantalum_pentoxide",
            5,
            "amphoteric",
            3
        ),
        Oxide(
            "V2O5",
            "vanadium_5_oxide",
            5,
            "amphoteric",
            2
        ),
        Oxide(
            "CrO3",
            "chromium_trioxide",
            6,
            "acidic",
            2
        ),
        Oxide(
            "ReO3",
            "rhenium_trioxide",
            6,
            "acidic",
            3
        ),
        Oxide(
            "SeO3",
            "selenium_trioxide",
            6,
            "acidic",
            2
        ),
        Oxide(
            "SO3",
            "sulfur_trioxide",
            6,
            "acidic",
            1
        ),
        Oxide(
            "TeO3",
            "tellurium_trioxide",
            6,
            "acidic",
            3
        ),
        Oxide(
            "WO3",
            "tungsten_trioxide",
            6,
            "acidic",
            2
        ),
        Oxide(
            "UO3",
            "uranium_trioxide",
            6,
            "amphoteric",
            3
        ),
        Oxide(
            "XeO3",
            "xenon_trioxide",
            6,
            "acidic",
            3
        ),
        Oxide(
            "Cl2O7",
            "dichlorine_heptoxide",
            7,
            "acidic",
            2
        ),
        Oxide(
            "Mn2O7",
            "manganese_heptoxide",
            7,
            "acidic",
            3
        ),
        Oxide(
            "Re2O7",
            "rhenium_7_oxide",
            7,
            "acidic",
            3
        ),
        Oxide(
            "Tc2O7",
            "technetium_7_oxide",
            7,
            "acidic",
            3
        ),
        Oxide(
            "OsO4",
            "osmium_tetroxide",
            8,
            "acidic",
            3
        ),
        Oxide(
            "RuO4",
            "ruthenium_tetroxide",
            8,
            "acidic",
            3
        ),
        Oxide(
            "XeO4",
            "xenon_tetroxide",
            8,
            "acidic",
            3
        ),
        Oxide(
            "Sb2O4",
            "antimony_tetroxide",
            0,
            "mixed",
            3
        ),
        Oxide(
            "Co3O4",
            "cobalt_2_3_oxide",
            0,
            "mixed",
            2
        ),
        Oxide(
            "Eu3O4",
            "europium_2_3_oxide",
            0,
            "mixed",
            3
        ),
        Oxide(
            "Fe3O4",
            "iron_2_3_oxide",
            0,
            "mixed",
            1
        ),
        Oxide(
            "Pb3O4",
            "lead_2_4_oxide",
            0,
            "mixed",
            2
        ),
        Oxide(
            "Mn3O4",
            "manganese_2_3_oxide",
            0,
            "mixed",
            2
        ),
        Oxide(
            "Ag2O2",
            "silver_1_3_oxide",
            0,
            "mixed",
            3
        ),
        Oxide(
            "U3O8",
            "triuranium_octoxide",
            0,
            "mixed",
            3
        ),
        Oxide(
            "C3O2",
            "carbon_suboxide",
            0,
            "mixed",
            3
        ),
        Oxide(
            "Pr6O11",
            "praseodymium_3_4_oxide",
            0,
            "mixed",
            3
        ),
        Oxide(
            "Tb4O7",
            "terbium_3_4_oxide",
            0,
            "mixed",
            3
        ),
        Oxide(
            "Al2O",
            "aluminium_1_oxide",
            1,
            "basic",
            3
        ),
        Oxide(
            "S2O",
            "disulfur_monoxide",
            1,
            "non_salt_forming",
            3
        ),
        Oxide(
            "N2O",
            "nitrous_oxide",
            1,
            "non_salt_forming",
            2
        )
    )
}