package selflearning.chemistree.domain.chemistry.inorganic.acids

object Acids {

    val acids = sequenceOf(
        Acid(
            "HCl",
            "hydrochloric",
            "chloride",
            "Cl",
            -1,
            "",
            1
        ),
        Acid(
            "HClO",
            "hypochlorous",
            "hypochlorite",
            "ClO",
            -1,
            "",
            2
        ),
        Acid(
            "HClO2",
            "chlorous",
            "chlorite",
            "ClO2",
            -1,
            "",
            2
        ),
        Acid(
            "HClO3",
            "chloric",
            "chlorate",
            "ClO3",
            -1,
            "",
            2
        ),
        Acid(
            "HClO4",
            "perchloric",
            "perchlorate",
            "ClO4",
            -1,
            "",
            2
        ),
        Acid(
            "HBr",
            "hydrobromic",
            "bromide",
            "Br",
            -1,
            "",
            1
        ),
        Acid(
            "HBrO",
            "hypobromous",
            "hypobromite",
            "BrO",
            -1,
            "",
            2
        ),
        Acid(
            "HBrO2",
            "bromous",
            "bromite",
            "BrO2",
            -1,
            "",
            2
        ),
        Acid(
            "HBrO3",
            "bromic",
            "bromate",
            "BrO3",
            -1,
            "",
            2
        ),
        Acid(
            "HBrO4",
            "perbromic",
            "perbromate",
            "BrO4",
            -1,
            "",
            2
        ),
        Acid(
            "HI",
            "hydroiodic",
            "iodide",
            "I",
            -1,
            "",
            1
        ),
        Acid(
            "HIO",
            "hypoiodous",
            "hypoiodite",
            "IO",
            -1,
            "",
            2
        ),
        Acid(
            "HIO2",
            "iodous",
            "iodite",
            "IO2",
            -1,
            "",
            2
        ),
        Acid(
            "HIO3",
            "iodic",
            "iodate",
            "IO3",
            -1,
            "",
            2
        ),
        Acid(
            "HIO4",
            "periodic",
            "periodate",
            "IO4",
            -1,
            "",
            2
        ),
        Acid(
            "HF",
            "hydrofluoric",
            "fluoride",
            "F",
            -1,
            "",
            1
        ),
        Acid(
            "HFO",
            "hypofluorous",
            "hypofluorite",
            "FO",
            -1,
            "",
            3
        ),
        Acid(
            "H2S",
            "hydrosulfuric",
            "hydrosulfate",
            "S",
            -2,
            "",
            1
        ),
        Acid(
            "H2SO2",
            "hyposulfurous",
            "hyposulfite",
            "SO2",
            -2,
            "",
            3
        ),
        Acid(
            "H2SO3",
            "sulfurous",
            "sulfite",
            "SO3",
            -2,
            "",
            1
        ),
        Acid(
            "H2SO4",
            "sulfuric",
            "sulfate",
            "SO4",
            -2,
            "",
            1
        ),
        Acid(
            "H2SO5",
            "persulfuric",
            "persulfate",
            "SO5",
            -2,
            "",
            3
        ),
        Acid(
            "H2S2O3",
            "thiosulfuric",
            "thiosulfate",
            "S2O3",
            -2,
            "",
            2
        ),
        Acid(
            "H2S2O4",
            "dithionous",
            "dithionite",
            "S2O4",
            -2,
            "",
            3
        ),
        Acid(
            "H2S2O5",
            "disulfurous",
            "disulfite",
            "S2O5",
            -2,
            "",
            3
        ),
        Acid(
            "H2S2O6",
            "dithionic",
            "dithionate",
            "S2O6",
            -2,
            "",
            3
        ),
        Acid(
            "H2S2O7",
            "pyrosulfuric",
            "pyrosulfate",
            "S2O7",
            -2,
            "",
            3
        ),
        Acid(
            "H2S2O8",
            "peroxydisulfuric",
            "peroxydisulfate",
            "S2O8",
            -2,
            "",
            3
        ),
        Acid(
            "H2S3O6",
            "trithionic",
            "trithionate",
            "S3O6",
            -2,
            "",
            3
        ),
        Acid(
            "H2S4O6",
            "tetrathionic",
            "tetrathionate",
            "S4O6",
            -2,
            "",
            2
        ),
        Acid(
            "H2S5O6",
            "pentathionic",
            "pentathionate",
            "S5O6",
            -2,
            "",
            3
        ),
        Acid(
            "HN3",
            "hydrazoic",
            "azide",
            "N3",
            -1,
            "",
            2
        ),
        Acid(
            "H2N2O2",
            "hyponitrous",
            "hyponitrite",
            "N2O2",
            -2,
            "",
            3
        ),
        Acid(
            "HNO2",
            "nitrous",
            "nitrite",
            "NO2",
            -1,
            "",
            1
        ),
        Acid(
            "HNO3",
            "nitric",
            "nitrate",
            "NO3",
            -1,
            "",
            1
        ),
        Acid(
            "H3PO2",
            "hypophosphous",
            "hypophosphite",
            "H2PO2",
            -1,
            "",
            2
        ),
        Acid(
            "H3PO3",
            "phosphorous",
            "phosphite",
            "HPO3",
            -2,
            "",
            2
        ),
        Acid(
            "H3PO4",
            "phosphoric",
            "phosphate",
            "PO4",
            -3,
            "",
            1
        ),
        Acid(
            "H4P2O7",
            "pyrophosphoric",
            "pyrophosphate",
            "P2O7",
            -4,
            "",
            3
        ),
        Acid(
            "HPO3",
            "metaphosphoric",
            "metaphosphate",
            "PO3",
            -1,
            "",
            2
        ),
        Acid(
            "H4P2O6",
            "hypophosphoric",
            "hypophosphate",
            "P2O6",
            -4,
            "",
            3
        ),
        Acid(
            "H2CO3",
            "carbonic",
            "carbonate",
            "CO3",
            -2,
            "",
            1
        ),
        Acid(
            "H2CrO4",
            "chromic",
            "chromate",
            "CrO4",
            -2,
            "",
            2
        ),
        Acid(
            "H2Cr2O7",
            "dichromic",
            "dichromate",
            "Cr2O7",
            -2,
            "",
            2
        ),
        Acid(
            "H2Se",
            "hydroselenic",
            "selenide",
            "Se",
            -2,
            "",
            3
        ),
        Acid(
            "H2SeO3",
            "selenous",
            "selenite",
            "SeO3",
            -2,
            "",
            3
        ),
        Acid(
            "H2SeO4",
            "selenic",
            "selenate",
            "SeO4",
            -2,
            "",
            3
        ),
        Acid(
            "H2SiO3",
            "silicic",
            "silicate",
            "SiO3",
            -2,
            "",
            1
        ),
        Acid(
            "H4SiO4",
            "orthosilicic",
            "orthosilicate",
            "SiO4",
            -4,
            "",
            3
        ),
        Acid(
            "H2SiF6",
            "silicofluoric",
            "silicofluorate",
            "SiF6",
            -2,
            "",
            3
        ),
        Acid(
            "HMnO4",
            "permanganic",
            "permanganate",
            "MnO4",
            -1,
            "",
            2
        ),
        Acid(
            "H2MnO4",
            "manganic",
            "manganate",
            "MnO4",
            -2,
            "",
            2
        ),
        Acid(
            "H3BO3",
            "boric",
            "borate",
            "BO3",
            -3,
            "",
            2
        ),
        Acid(
            "H2B4O7",
            "tetraboric",
            "tetraborate",
            "B4O7",
            -2,
            "",
            2
        ),
        Acid(
            "HSbO3",
            "antimonic",
            "antimonate",
            "SbO3",
            -1,
            "",
            3
        ),
        Acid(
            "H2TeO3",
            "tellurous",
            "tellurite",
            "TeO3",
            -2,
            "",
            3
        ),
        Acid(
            "H6TeO6",
            "telluric",
            "tellurate",
            "TeO6",
            -6,
            "",
            3
        ),
        Acid(
            "H2MoO4",
            "molybdic",
            "molybdate",
            "MoO4",
            -2,
            "",
            3
        ),
        Acid(
            "H4XeO6",
            "perxenic",
            "perxenate",
            "XeO6",
            -4,
            "",
            3
        ),
        Acid(
            "H2XeO4",
            "xenic",
            "xenate",
            "XeO4",
            -2,
            "",
            3
        ),
        Acid(
            "H2WO4",
            "tungstic",
            "tungstate",
            "WO4",
            -2,
            "",
            3
        ),
        Acid(
            "H2TiO3",
            "titanic",
            "titanate",
            "TiO3",
            -2,
            "",
            3
        ),
        Acid(
            "H3AsO4",
            "arsenica",
            "arsenate",
            "AsO4",
            -3,
            "",
            3
        ),
        Acid(
            "HTcO4",
            "pertechnetic",
            "pertechnetate",
            "TcO4",
            -1,
            "",
            3
        ),
        Acid(
            "H2SnO3",
            "metastannic",
            "metastannate",
            "SnO3",
            -2,
            "",
            3
        ),
        Acid(
            "HNCO",
            "cyanic",
            "cyanate",
            "NCO",
            -1,
            "",
            2
        ),
        Acid(
            "HCN",
            "hydrocyanic",
            "cyanide",
            "CN",
            -1,
            "",
            2
        ),
        Acid(
            "HSCN",
            "thiocyanic",
            "thiocyanate",
            "SCN",
            -1,
            "",
            2
        ),
        Acid(
            "H2UO4",
            "uranic",
            "uranate",
            "UO4",
            -2,
            "",
            3
        ),
        Acid(
            "H2U2O7",
            "diuranic",
            "diuranate",
            "U2O7",
            -2,
            "",
            3
        ),
        Acid(
            "HReO4",
            "perrhenic",
            "perrhenate",
            "ReO4",
            -1,
            "",
            3
        ),
        Acid(
            "HAsO2",
            "arsenous",
            "arsenite",
            "AsO2",
            -1,
            "",
            3
        )
    )
}