package selflearning.chemistree.domain.chemistry.elements

object Elements {

    val elements = listOf(
        Element(
            1,
            "H",
            "hydrogen",
            1.0079,
            "reactiveNonmetal"
        ),
        Element(
            2,
            "He",
            "helium",
            4.0026,
            "nobleGas"
        ),
        Element(
            3,
            "Li",
            "lithium",
            6.941,
            "alkaliMetal"
        ),
        Element(
            4,
            "Be",
            "beryllium",
            9.0121,
            "alkalineEarthMetal"
        ),
        Element(
            5,
            "B",
            "boron",
            10.811,
            "metalloid"
        ),
        Element(
            6,
            "C",
            "carbon",
            12.0107,
            "reactiveNonmetal"
        ),
        Element(
            7,
            "N",
            "nitrogen",
            14.0067,
            "reactiveNonmetal"),
        Element(
            8,
            "O",
            "oxygen",
            15.9994,
            "reactiveNonmetal"),
        Element(
            9,
            "F",
            "fluorine",
            18.9984,
            "reactiveNonmetal"),
        Element(
            10,
            "Ne",
            "neon",
            20.1797,
            "nobleGas"),
        Element(
            11,
            "Na",
            "sodium",
            22.9897,
            "alkaliMetal"),
        Element(
            12,
            "Mg",
            "magnesium",
            24.305,
            "alkalineEarthMetal"),
        Element(
            13,
            "Al",
            "aluminum",
            26.9815,
            "postTransitionMetal"),
        Element(
            14,
            "Si",
            "silicon",
            28.0855,
            "metalloid"),
        Element(
            15,
            "P",
            "phosphorus",
            30.9737,
            "reactiveNonmetal"),
        Element(
            16,
            "S",
            "sulfur",
            32.065,
            "reactiveNonmetal"),
        Element(
            17,
            "Cl",
            "chlorine",
            35.453,
            "reactiveNonmetal"),
        Element(
            18,
            "Ar",
            "argon",
            39.948,
            "nobleGas"),
        Element(
            19,
            "K",
            "potassium",
            39.0983,
            "alkaliMetal"),
        Element(
            20,
            "Ca",
            "calcium",
            40.078,
            "alkalineEarthMetal"),
        Element(
            21,
            "Sc",
            "scandium",
            44.9559,
            "transitionMetal"),
        Element(
            22,
            "Ti",
            "titanium",
            47.867,
            "transitionMetal"),
        Element(
            23,
            "V",
            "vanadium",
            50.9415,
            "transitionMetal"),
        Element(
            24,
            "Cr",
            "chromium",
            51.9961,
            "transitionMetal"),
        Element(
            25,
            "Mn",
            "manganese",
            54.938,
            "transitionMetal"),
        Element(
            26,
            "Fe",
            "iron",
            55.845,
            "transitionMetal"),
        Element(
            27,
            "Co",
            "cobalt",
            58.9331,
            "transitionMetal"),
        Element(
            28,
            "Ni",
            "nickel",
            58.6934,
            "transitionMetal"),
        Element(
            29,
            "Cu",
            "copper",
            63.546,
            "transitionMetal"),
        Element(
            30,
            "Zn",
            "zinc",
            65.409,
            "postTransitionMetal"),
        Element(
            31,
            "Ga",
            "gallium",
            69.723,
            "postTransitionMetal"),
        Element(
            32,
            "Ge",
            "germanium",
            72.630,
            "metalloid"),
        Element(
            33,
            "As",
            "arsenic",
            74.9216,
            "metalloid"),
        Element(
            34,
            "Se",
            "selenium",
            78.971,
            "reactiveNonmetal"),
        Element(
            35,
            "Br",
            "bromine",
            79.904,
            "reactiveNonmetal"),
        Element(36, "Kr", "krypton", 83.798, "nobleGas"),
        Element(37, "Rb", "rubidium", 85.4678, "alkaliMetal"),
        Element(38, "Sr", "strontium", 87.62, "alkalineEarthMetal"),
        Element(39, "Y", "yttrium", 88.905, "transitionMetal"),
        Element(40, "Zr", "zirconium", 91.224, "transitionMetal"),
        Element(41, "Nb", "niobium", 92.906, "transitionMetal"),
        Element(42, "Mo", "molybdenum", 95.94, "transitionMetal"),
        Element(43, "Tc", "technetium", 97.906, "transitionMetal"),
        Element(44, "Ru", "ruthenium", 101.07, "transitionMetal"),
        Element(45, "Rh", "rhodium", 102.905, "transitionMetal"),
        Element(46, "Pd", "palladium", 106.42, "transitionMetal"),
        Element(47, "Ag", "silver", 107.868, "transitionMetal"),
        Element(48, "Cd", "cadmium", 112.411, "postTransitionMetal"),
        Element(49, "In", "indium", 114.818, "postTransitionMetal"),
        Element(50, "Sn", "tin", 118.71, "postTransitionMetal"),
        Element(51, "Sb", "antimony", 121.76, "metalloid"),
        Element(52, "Te", "tellurium", 127.6, "metalloid"),
        Element(53, "I", "iodine", 126.904, "reactiveNonmetal"),
        Element(54, "Xe", "xenon", 131.293, "nobleGas"),
        Element(55, "Cs", "cesium", 132.905, "alkaliMetal"),
        Element(56, "Ba", "barium", 137.327, "alkalineEarthMetal"),
        Element(57, "La", "lanthanum", 138.905, "lanthanide"),
        Element(58, "Ce", "cerium", 140.116, "lanthanide"),
        Element(59, "Pr", "praseodynium", 140.904, "lanthanide"),
        Element(60, "Nd", "neodymium", 144.242, "lanthanide"),
        Element(61, "Pm", "promethium", 144.915, "lanthanide"),
        Element(62, "Sm", "samarium", 150.36, "lanthanide"),
        Element(63, "Eu", "europium", 151.964, "lanthanide"),
        Element(64, "Gd", "gadolinium", 157.25, "lanthanide"),
        Element(65, "Tb", "terbium", 158.925, "lanthanide"),
        Element(66, "Dy", "dysprosium", 162.5, "lanthanide"),
        Element(67, "Ho", "holmium", 164.93, "lanthanide"),
        Element(68, "Er", "erbium", 167.259, "lanthanide"),
        Element(69, "Tm", "thulium", 168.934, "lanthanide"),
        Element(70, "Yb", "ytterbium", 173.04, "lanthanide"),
        Element(71, "Lu", "lutetium", 174.967, "lanthanide"),
        Element(72, "Hf", "hafnium", 178.49, "transitionMetal"),
        Element(73, "Ta", "tantalum", 180.947, "transitionMetal"),
        Element(74, "W", "tungsten", 183.84, "transitionMetal"),
        Element(75, "Re", "rhenium", 186.207, "transitionMetal"),
        Element(76, "Os", "osmium", 190.23, "transitionMetal"),
        Element(77, "Ir", "iridium", 192.217, "transitionMetal"),
        Element(78, "Pt", "platinum", 195.084, "transitionMetal"),
        Element(79, "Au", "gold", 196.966, "transitionMetal"),
        Element(80, "Hg", "mercury", 200.59, "postTransitionMetal"),
        Element(81, "Tl", "thallium", 204.383, "postTransitionMetal"),
        Element(82, "Pb", "lead", 207.2, "postTransitionMetal"),
        Element(83, "Bi", "bismuth", 208.980, "postTransitionMetal"),
        Element(84, "Po", "polonium", 208.9824, "postTransitionMetal"),
        Element(85, "At", "astatine", 209.9871, "metalloid"),
        Element(86, "Rn", "radon", 222.0176, "nobleGas"),
        Element(87, "Fr", "francium", 223.0197, "alkaliMetal"),
        Element(88, "Ra", "radium", 226.0254, "alkalineEarthMetal"),
        Element(89, "Ac", "actinium", 227.0278, "actinide"),
        Element(90, "Th", "thorium", 232.038, "actinide"),
        Element(91, "Pa", "protactinium", 231.0358, "actinide"),
        Element(92, "U", "uranium", 238.0289, "actinide"),
        Element(93, "Np", "neptunium", 237.0482, "actinide"),
        Element(94, "Pu", "plutonium", 244.0642, "actinide"),
        Element(95, "Am", "americium", 243.0614, "actinide"),
        Element(96, "Cm", "curium", 247.0703, "actinide"),
        Element(97, "Bk", "berklium", 247.0703, "actinide"),
        Element(98, "Cf", "californium", 251.0796, "actinide"),
        Element(99, "Es", "einsteinium", 252.0829, "actinide"),
        Element(100, "Fm", "fermium", 257.0951, "actinide"),
        Element(101, "Md", "mendelevium", 258.0951, "actinide"),
        Element(102, "No", "nobelium", 259.1009, "actinide"),
        Element(103, "Lr", "lawrencium", 266.1193, "actinide"),
        Element(104, "Rf", "rutherfordium", 267.0, "transitionMetal"),
        Element(105, "Db", "dubnium", 262.0, "transitionMetal"),
        Element(106, "Sg", "seaborgium", 269.0, "transitionMetal"),
        Element(107, "Bh", "bohrium", 270.0, "transitionMetal"),
        Element(108, "Hs", "hassium", 269.0, "transitionMetal"),
        Element(109, "Mt", "meitnerium", 278.0, "transitionMetal"),
        Element(110, "Ds", "darmstadtium", 281.1620, "transitionMetal"),
        Element(111, "Rg", "roentgenium", 281.1684, "transitionMetal"),
        Element(112, "Cn", "copernicium", 285.1744, "transitionMetal"),
        Element(113, "Nh", "nihonium", 286.181, "postTransitionMetal"),
        Element(114, "Fl", "flerovium", 289.1904, "postTransitionMetal"),
        Element(115, "Mc", "moscovium", 290.1943, "postTransitionMetal"),
        Element(116, "Lv", "livermorium", 293.2045, "postTransitionMetal"),
        Element(117, "Ts", "tennessine", 294.2104, "postTransitionMetal"),
        Element(118, "Og", "oganesson", 294.2139, "nobleGas"),
    )
}