package selflearning.chemistree.domain.chemistry.inorganic.bases

object Bases {

    val bases = sequenceOf(
        Base(
            "NH4OH",
            "ammonium",
            1,
            "NH4",
            "",
            1
        ),
        Base(
            "CsOH",
            "cesium1",
            1,
            "Cs",
            "",
            1
        ),
        Base(
            "CuOH",
            "copper1",
            1,
            "Cu",
            "",
            2
        ),
        Base(
            "AuOH",
            "gold1",
            1,
            "Au",
            "",
            2
        ),
        Base(
            "InOH",
            "indium1",
            1,
            "In",
            "",
            3
        ),
        Base(
            "LiOH",
            "lithium1",
            1,
            "Li",
            "",
            1
        ),
//        Base(
//            "NiOOH",
//            "nickel1",
//            1,
//            "NH4",
//            "",
//            3
//        ),
        Base(
            "KOH",
            "potassium1",
            1,
            "K",
            "",
            1
        ),
        Base(
            "RbOH",
            "rubidium1",
            1,
            "Rb",
            "",
            2
        ),
        Base(
            "AgOH",
            "silver1",
            1,
            "Ag",
            "",
            1
        ),
        Base(
            "NaOH",
            "sodium1",
            1,
            "Na",
            "",
            1
        ),
        Base(
            "TlOH",
            "thallium1",
            1,
            "Tl",
            "",
            3
        ),
        Base(
            "Be(OH)2",
            "beryllium2",
            2,
            "Be",
            "",
            1
        ),
        Base(
            "Cd(OH)2",
            "cadmium2",
            2,
            "Cd",
            "",
            3
        ),
        Base(
            "Ca(OH)2",
            "calcium2",
            2,
            "Ca",
            "",
            1
        ),
        Base(
            "Cr(OH)2",
            "chromium2",
            2,
            "Cr",
            "",
            2
        ),
        Base(
            "Co(OH)2",
            "cobalt2",
            2,
            "Co",
            "",
            2
        ),
        Base(
            "Ga(OH)2",
            "gallium2",
            2,
            "Ga",
            "",
            3
        ),
        Base(
            "Cu(OH)2",
            "copper2",
            2,
            "Cu",
            "",
            1
        ),
        Base(
            "In(OH)2",
            "indium2",
            2,
            "In",
            "",
            3
        ),
        Base(
            "Fe(OH)2",
            "iron2",
            2,
            "Fe",
            "",
            1
        ),
        Base(
            "Pb(OH)2",
            "lead2",
            2,
            "Pb",
            "",
            2
        ),
        Base(
            "Mg(OH)2",
            "magnesium2",
            2,
            "Mg",
            "",
            1
        ),
        Base(
            "Mn(OH)2",
            "manganese2",
            2,
            "Mn",
            "",
            2
        ),
        Base(
            "Hg(OH)2",
            "mercury2",
            2,
            "Hg",
            "",
            2
        ),
        Base(
            "Ni(OH)2",
            "nickel2",
            2,
            "Ni",
            "",
            2
        ),
        Base(
            "Ba(OH)2",
            "barium2",
            2,
            "Ba",
            "",
            1
        ),
        Base(
            "Pd(OH)2",
            "palladium2",
            2,
            "Pd",
            "",
            2
        ),
        Base(
            "Pt(OH)2",
            "platinum2",
            2,
            "Pt",
            "",
            2
        ),
        Base(
            "Ra(OH)2",
            "radium2",
            2,
            "Ra",
            "",
            3
        ),
        Base(
            "Sr(OH)2",
            "strontium2",
            2,
            "Sr",
            "",
            2
        ),
        Base(
            "Tc(OH)2",
            "technetium2",
            2,
            "Tc",
            "",
            3
        ),
        Base(
            "Sn(OH)2",
            "tin2",
            2,
            "Sn",
            "",
            2
        ),
        Base(
            "Ti(OH)2",
            "titanium2",
            2,
            "Ti",
            "",
            3
        ),
        Base(
            "W(OH)2",
            "tungsten2",
            2,
            "W",
            "",
            3
        ),
        Base(
            "V(OH)2",
            "vanadium2",
            2,
            "V",
            "",
            2
        ),
        Base(
            "Zn(OH)2",
            "zinc2",
            2,
            "Zn",
            "",
            1
        ),
        Base(
            "UO2(OH)2",
            "uranyl",
            2,
            "UO2",
            "",
            3
        ),
        Base(
            "Al(OH)3",
            "aluminum3",
            3,
            "Al",
            "",
            1
        ),
        Base(
            "As(OH)3",
            "arsenic3",
            3,
            "As",
            "",
            3
        ),
        Base(
            "Bi(OH)3",
            "bismuth3",
            3,
            "Bi",
            "",
            3
        ),
        Base(
            "Ce(OH)3",
            "cerium3",
            3,
            "Ce",
            "",
            3
        ),
        Base(
            "Cr(OH)3",
            "chromium3",
            3,
            "Cr",
            "",
            2
        ),
        Base(
            "Co(OH)3",
            "cobalt3",
            3,
            "Co",
            "",
            2
        ),
        Base(
            "Ga(OH)3",
            "gallium3",
            3,
            "Ga",
            "",
            3
        ),
        Base(
            "Au(OH)3",
            "gold3",
            3,
            "Au",
            "",
            2
        ),
        Base(
            "In(OH)3",
            "indium3",
            3,
            "In",
            "",
            3
        ),
        Base(
            "Ir(OH)3",
            "iridium3",
            3,
            "Ir",
            "",
            3
        ),
        Base(
            "La(OH)3",
            "lanthanum3",
            3,
            "La",
            "",
            3
        ),
        Base(
            "Fe(OH)3",
            "iron3",
            3,
            "Fe",
            "",
            1
        ),
        Base(
            "Mn(OH)3",
            "manganese3",
            3,
            "Mn",
            "",
            2
        ),
        Base(
            "Mo(OH)3",
            "molybdenum3",
            3,
            "Mo",
            "",
            2
        ),
        Base(
            "Nd(OH)3",
            "neodymium3",
            3,
            "Nd",
            "",
            3
        ),
        Base(
            "Ni(OH)3",
            "nickel3",
            3,
            "Ni",
            "",
            2
        ),
        Base(
            "Nb(OH)3",
            "niobium3",
            3,
            "Nb",
            "",
            2
        ),
        Base(
            "Ru(OH)3",
            "ruthenium3",
            3,
            "Ru",
            "",
            3
        ),
        Base(
            "Sc(OH)3",
            "scandium3",
            3,
            "Sc",
            "",
            2
        ),
        Base(
            "Tl(OH)3",
            "thallium3",
            3,
            "Tl",
            "",
            3
        ),
        Base(
            "Ti(OH)3",
            "titanium3",
            3,
            "Ti",
            "",
            3
        ),
        Base(
            "V(OH)3",
            "vanadium3",
            3,
            "V",
            "",
            3
        ),
        Base(
            "Yb(OH)3",
            "ytterbium3",
            3,
            "Yb",
            "",
            3
        ),
        Base(
            "Y(OH)3",
            "yttrium3",
            3,
            "Y",
            "",
            3
        ),
        Base(
            "Pb(OH)4",
            "lead4",
            4,
            "Pb",
            "",
            3
        ),
        Base(
            "Mn(OH)4",
            "manganese4",
            4,
            "Mn",
            "",
            3
        ),
        Base(
            "Os(OH)4",
            "osmium4",
            4,
            "Os",
            "",
            3
        ),
        Base(
            "Pd(OH)4",
            "palladium4",
            4,
            "Pd",
            "",
            3
        ),
        Base(
            "Pt(OH)4",
            "platinum4",
            4,
            "Pt",
            "",
            3
        ),
        Base(
            "Pu(OH)4",
            "plutonium4",
            4,
            "Pu",
            "",
            3
        ),
        Base(
            "Si(OH)4",
            "silicon4",
            4,
            "Si",
            "",
            3
        ),
        Base(
            "Th(OH)4",
            "thorium4",
            4,
            "Th",
            "",
            3
        ),
        Base(
            "Sn(OH)4",
            "tin4",
            4,
            "Sn",
            "",
            2
        ),
        Base(
            "Ti(OH)4",
            "titanium4",
            4,
            "Ti",
            "",
            2
        ),
        Base(
            "Zr(OH)4",
            "zirconium4",
            4,
            "Zr",
            "",
            3
        )
    )
}