package com.selflearning.chemistree.ui.home.mendeleevTable.LongTable;

import androidx.lifecycle.ViewModelProviders;

import android.app.Dialog;
import android.content.Intent;
import android.os.Bundle;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.fragment.app.Fragment;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import android.widget.Toast;

import com.selflearning.chemistree.activities.ElementInfoActivity;
import com.selflearning.chemistree.R;

import java.util.ArrayList;
import java.util.List;

public class LongTable extends Fragment {

    private LongTableViewModel mViewModel;
    private Toast toast;
    Dialog dialog;

    private LinearLayout linearLayout1;
    private LinearLayout linearLayout2;
    private LinearLayout linearLayout3;
    private LinearLayout linearLayout4;
    private LinearLayout linearLayout5;
    private LinearLayout linearLayout6;
    private LinearLayout linearLayout7;
    private LinearLayout linearLayout8;
    private LinearLayout linearLayout9;
    private LinearLayout linearLayout10;
    private LinearLayout linearLayout11;
    private LinearLayout linearLayout12;
    private LinearLayout linearLayout13;
    private LinearLayout linearLayout14;
    private LinearLayout linearLayout15;
    private LinearLayout linearLayout16;
    private LinearLayout linearLayout17;
    private LinearLayout linearLayout18;
    private LinearLayout linearLayout19;
    private LinearLayout linearLayout20;
    private LinearLayout linearLayout21;
    private LinearLayout linearLayout22;
    private LinearLayout linearLayout23;
    private LinearLayout linearLayout24;
    private LinearLayout linearLayout25;
    private LinearLayout linearLayout26;
    private LinearLayout linearLayout27;
    private LinearLayout linearLayout28;
    private LinearLayout linearLayout29;
    private LinearLayout linearLayout30;
    private LinearLayout linearLayout31;
    private LinearLayout linearLayout32;
    private LinearLayout linearLayout33;
    private LinearLayout linearLayout34;
    private LinearLayout linearLayout35;
    private LinearLayout linearLayout36;
    private LinearLayout linearLayout37;
    private LinearLayout linearLayout38;
    private LinearLayout linearLayout39;
    private LinearLayout linearLayout40;
    private LinearLayout linearLayout41;
    private LinearLayout linearLayout42;
    private LinearLayout linearLayout43;
    private LinearLayout linearLayout44;
    private LinearLayout linearLayout45;
    private LinearLayout linearLayout46;
    private LinearLayout linearLayout47;
    private LinearLayout linearLayout48;
    private LinearLayout linearLayout49;
    private LinearLayout linearLayout50;
    private LinearLayout linearLayout51;
    private LinearLayout linearLayout52;
    private LinearLayout linearLayout53;
    private LinearLayout linearLayout54;
    private LinearLayout linearLayout55;
    private LinearLayout linearLayout56;
    private LinearLayout linearLayout57;
    private LinearLayout linearLayout58;
    private LinearLayout linearLayout59;
    private LinearLayout linearLayout60;
    private LinearLayout linearLayout61;
    private LinearLayout linearLayout62;
    private LinearLayout linearLayout63;
    private LinearLayout linearLayout64;
    private LinearLayout linearLayout65;
    private LinearLayout linearLayout66;
    private LinearLayout linearLayout67;
    private LinearLayout linearLayout68;
    private LinearLayout linearLayout69;
    private LinearLayout linearLayout70;
    private LinearLayout linearLayout71;
    private LinearLayout linearLayout72;
    private LinearLayout linearLayout73;
    private LinearLayout linearLayout74;
    private LinearLayout linearLayout75;
    private LinearLayout linearLayout76;
    private LinearLayout linearLayout77;
    private LinearLayout linearLayout78;
    private LinearLayout linearLayout79;
    private LinearLayout linearLayout80;
    private LinearLayout linearLayout81;
    private LinearLayout linearLayout82;
    private LinearLayout linearLayout83;
    private LinearLayout linearLayout84;
    private LinearLayout linearLayout85;
    private LinearLayout linearLayout86;
    private LinearLayout linearLayout87;
    private LinearLayout linearLayout88;
    private LinearLayout linearLayout89;
    private LinearLayout linearLayout90;
    private LinearLayout linearLayout91;
    private LinearLayout linearLayout92;
    private LinearLayout linearLayout93;
    private LinearLayout linearLayout94;
    private LinearLayout linearLayout95;
    private LinearLayout linearLayout96;
    private LinearLayout linearLayout97;
    private LinearLayout linearLayout98;
    private LinearLayout linearLayout99;
    private LinearLayout linearLayout100;
    private LinearLayout linearLayout101;
    private LinearLayout linearLayout102;
    private LinearLayout linearLayout103;
    private LinearLayout linearLayout104;
    private LinearLayout linearLayout105;
    private LinearLayout linearLayout106;
    private LinearLayout linearLayout107;
    private LinearLayout linearLayout108;
    private LinearLayout linearLayout109;
    private LinearLayout linearLayout110;
    private LinearLayout linearLayout111;
    private LinearLayout linearLayout112;
    private LinearLayout linearLayout113;
    private LinearLayout linearLayout114;
    private LinearLayout linearLayout115;
    private LinearLayout linearLayout116;
    private LinearLayout linearLayout117;
    private LinearLayout linearLayout118;

    private List<LinearLayout> linearLayoutList = new ArrayList<>();

    public static LongTable newInstance() {
        return new LongTable();
    }

    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container,
                             @Nullable Bundle savedInstanceState) {
        View root = inflater.inflate(R.layout.long_table_fragment, container, false);

        linearLayout1 = root.findViewById(R.id.element1);
        linearLayout2 = root.findViewById(R.id.element2);
        linearLayout3 = root.findViewById(R.id.element3);
        linearLayout4 = root.findViewById(R.id.element4);
        linearLayout5 = root.findViewById(R.id.element5);
        linearLayout6 = root.findViewById(R.id.element6);
        linearLayout7 = root.findViewById(R.id.element7);
        linearLayout8 = root.findViewById(R.id.element8);
        linearLayout9 = root.findViewById(R.id.element9);
        linearLayout10 = root.findViewById(R.id.element10);
        linearLayout11 = root.findViewById(R.id.element11);
        linearLayout12 = root.findViewById(R.id.element12);
        linearLayout13 = root.findViewById(R.id.element13);
        linearLayout14 = root.findViewById(R.id.element14);
        linearLayout15 = root.findViewById(R.id.element15);
        linearLayout16 = root.findViewById(R.id.element16);
        linearLayout17 = root.findViewById(R.id.element17);
        linearLayout18 = root.findViewById(R.id.element18);
        linearLayout19 = root.findViewById(R.id.element19);
        linearLayout20 = root.findViewById(R.id.element20);
        linearLayout21 = root.findViewById(R.id.element21);
        linearLayout22 = root.findViewById(R.id.element22);
        linearLayout23 = root.findViewById(R.id.element23);
        linearLayout24 = root.findViewById(R.id.element24);
        linearLayout25 = root.findViewById(R.id.element25);
        linearLayout26 = root.findViewById(R.id.element26);
        linearLayout27 = root.findViewById(R.id.element27);
        linearLayout28 = root.findViewById(R.id.element28);
        linearLayout29 = root.findViewById(R.id.element29);
        linearLayout30 = root.findViewById(R.id.element30);
        linearLayout31 = root.findViewById(R.id.element31);
        linearLayout32 = root.findViewById(R.id.element32);
        linearLayout33 = root.findViewById(R.id.element33);
        linearLayout34 = root.findViewById(R.id.element34);
        linearLayout35 = root.findViewById(R.id.element35);
        linearLayout36 = root.findViewById(R.id.element36);
        linearLayout37 = root.findViewById(R.id.element37);
        linearLayout38 = root.findViewById(R.id.element38);
        linearLayout39 = root.findViewById(R.id.element39);
        linearLayout40 = root.findViewById(R.id.element40);
        linearLayout41 = root.findViewById(R.id.element41);
        linearLayout42 = root.findViewById(R.id.element42);
        linearLayout43 = root.findViewById(R.id.element43);
        linearLayout44 = root.findViewById(R.id.element44);
        linearLayout45 = root.findViewById(R.id.element45);
        linearLayout46 = root.findViewById(R.id.element46);
        linearLayout47 = root.findViewById(R.id.element47);
        linearLayout48 = root.findViewById(R.id.element48);
        linearLayout49 = root.findViewById(R.id.element49);
        linearLayout50 = root.findViewById(R.id.element50);
        linearLayout51 = root.findViewById(R.id.element51);
        linearLayout52 = root.findViewById(R.id.element52);
        linearLayout53 = root.findViewById(R.id.element53);
        linearLayout54 = root.findViewById(R.id.element54);
        linearLayout55 = root.findViewById(R.id.element55);
        linearLayout56 = root.findViewById(R.id.element56);
        linearLayout57 = root.findViewById(R.id.element57);
        linearLayout58 = root.findViewById(R.id.element58);
        linearLayout59 = root.findViewById(R.id.element59);
        linearLayout60 = root.findViewById(R.id.element60);
        linearLayout61 = root.findViewById(R.id.element61);
        linearLayout62 = root.findViewById(R.id.element62);
        linearLayout63 = root.findViewById(R.id.element63);
        linearLayout64 = root.findViewById(R.id.element64);
        linearLayout65 = root.findViewById(R.id.element65);
        linearLayout66 = root.findViewById(R.id.element66);
        linearLayout67 = root.findViewById(R.id.element67);
        linearLayout68 = root.findViewById(R.id.element68);
        linearLayout69 = root.findViewById(R.id.element69);
        linearLayout70 = root.findViewById(R.id.element70);
        linearLayout71 = root.findViewById(R.id.element71);
        linearLayout72 = root.findViewById(R.id.element72);
        linearLayout73 = root.findViewById(R.id.element73);
        linearLayout74 = root.findViewById(R.id.element74);
        linearLayout75 = root.findViewById(R.id.element75);
        linearLayout76 = root.findViewById(R.id.element76);
        linearLayout77 = root.findViewById(R.id.element77);
        linearLayout78 = root.findViewById(R.id.element78);
        linearLayout79 = root.findViewById(R.id.element79);
        linearLayout80 = root.findViewById(R.id.element80);
        linearLayout81 = root.findViewById(R.id.element81);
        linearLayout82 = root.findViewById(R.id.element82);
        linearLayout83 = root.findViewById(R.id.element83);
        linearLayout84 = root.findViewById(R.id.element84);
        linearLayout85 = root.findViewById(R.id.element85);
        linearLayout86 = root.findViewById(R.id.element86);
        linearLayout87 = root.findViewById(R.id.element87);
        linearLayout88 = root.findViewById(R.id.element88);
        linearLayout89 = root.findViewById(R.id.element89);
        linearLayout90 = root.findViewById(R.id.element90);
        linearLayout91 = root.findViewById(R.id.element91);
        linearLayout92 = root.findViewById(R.id.element92);
        linearLayout93 = root.findViewById(R.id.element93);
        linearLayout94 = root.findViewById(R.id.element94);
        linearLayout95 = root.findViewById(R.id.element95);
        linearLayout96 = root.findViewById(R.id.element96);
        linearLayout97 = root.findViewById(R.id.element97);
        linearLayout98 = root.findViewById(R.id.element98);
        linearLayout99 = root.findViewById(R.id.element99);
        linearLayout100 = root.findViewById(R.id.element100);
        linearLayout101 = root.findViewById(R.id.element101);
        linearLayout102 = root.findViewById(R.id.element102);
        linearLayout103 = root.findViewById(R.id.element103);
        linearLayout104 = root.findViewById(R.id.element104);
        linearLayout105 = root.findViewById(R.id.element105);
        linearLayout106 = root.findViewById(R.id.element106);
        linearLayout107 = root.findViewById(R.id.element107);
        linearLayout108 = root.findViewById(R.id.element108);
        linearLayout109 = root.findViewById(R.id.element109);
        linearLayout110 = root.findViewById(R.id.element110);
        linearLayout111 = root.findViewById(R.id.element111);
        linearLayout112 = root.findViewById(R.id.element112);
        linearLayout113 = root.findViewById(R.id.element113);
        linearLayout114 = root.findViewById(R.id.element114);
        linearLayout115 = root.findViewById(R.id.element115);
        linearLayout116 = root.findViewById(R.id.element116);
        linearLayout117 = root.findViewById(R.id.element117);
        linearLayout118 = root.findViewById(R.id.element118);
        linearLayoutList.add(linearLayout1);
        linearLayoutList.add(linearLayout2);
        linearLayoutList.add(linearLayout3);
        linearLayoutList.add(linearLayout4);
        linearLayoutList.add(linearLayout5);
        linearLayoutList.add(linearLayout6);
        linearLayoutList.add(linearLayout7);
        linearLayoutList.add(linearLayout8);
        linearLayoutList.add(linearLayout9);
        linearLayoutList.add(linearLayout10);
        linearLayoutList.add(linearLayout11);
        linearLayoutList.add(linearLayout12);
        linearLayoutList.add(linearLayout13);
        linearLayoutList.add(linearLayout14);
        linearLayoutList.add(linearLayout15);
        linearLayoutList.add(linearLayout16);
        linearLayoutList.add(linearLayout17);
        linearLayoutList.add(linearLayout18);
        linearLayoutList.add(linearLayout19);
        linearLayoutList.add(linearLayout20);
        linearLayoutList.add(linearLayout21);
        linearLayoutList.add(linearLayout22);
        linearLayoutList.add(linearLayout23);
        linearLayoutList.add(linearLayout24);
        linearLayoutList.add(linearLayout25);
        linearLayoutList.add(linearLayout26);
        linearLayoutList.add(linearLayout27);
        linearLayoutList.add(linearLayout28);
        linearLayoutList.add(linearLayout29);
        linearLayoutList.add(linearLayout30);
        linearLayoutList.add(linearLayout31);
        linearLayoutList.add(linearLayout32);
        linearLayoutList.add(linearLayout33);
        linearLayoutList.add(linearLayout34);
        linearLayoutList.add(linearLayout35);
        linearLayoutList.add(linearLayout36);
        linearLayoutList.add(linearLayout37);
        linearLayoutList.add(linearLayout38);
        linearLayoutList.add(linearLayout39);
        linearLayoutList.add(linearLayout40);
        linearLayoutList.add(linearLayout41);
        linearLayoutList.add(linearLayout42);
        linearLayoutList.add(linearLayout43);
        linearLayoutList.add(linearLayout44);
        linearLayoutList.add(linearLayout45);
        linearLayoutList.add(linearLayout46);
        linearLayoutList.add(linearLayout47);
        linearLayoutList.add(linearLayout48);
        linearLayoutList.add(linearLayout49);
        linearLayoutList.add(linearLayout50);
        linearLayoutList.add(linearLayout51);
        linearLayoutList.add(linearLayout52);
        linearLayoutList.add(linearLayout53);
        linearLayoutList.add(linearLayout54);
        linearLayoutList.add(linearLayout55);
        linearLayoutList.add(linearLayout56);
        linearLayoutList.add(linearLayout57);
        linearLayoutList.add(linearLayout58);
        linearLayoutList.add(linearLayout59);
        linearLayoutList.add(linearLayout60);
        linearLayoutList.add(linearLayout61);
        linearLayoutList.add(linearLayout62);
        linearLayoutList.add(linearLayout63);
        linearLayoutList.add(linearLayout64);
        linearLayoutList.add(linearLayout65);
        linearLayoutList.add(linearLayout66);
        linearLayoutList.add(linearLayout67);
        linearLayoutList.add(linearLayout68);
        linearLayoutList.add(linearLayout69);
        linearLayoutList.add(linearLayout70);
        linearLayoutList.add(linearLayout71);
        linearLayoutList.add(linearLayout72);
        linearLayoutList.add(linearLayout73);
        linearLayoutList.add(linearLayout74);
        linearLayoutList.add(linearLayout75);
        linearLayoutList.add(linearLayout76);
        linearLayoutList.add(linearLayout77);
        linearLayoutList.add(linearLayout78);
        linearLayoutList.add(linearLayout79);
        linearLayoutList.add(linearLayout80);
        linearLayoutList.add(linearLayout81);
        linearLayoutList.add(linearLayout82);
        linearLayoutList.add(linearLayout83);
        linearLayoutList.add(linearLayout84);
        linearLayoutList.add(linearLayout85);
        linearLayoutList.add(linearLayout86);
        linearLayoutList.add(linearLayout87);
        linearLayoutList.add(linearLayout88);
        linearLayoutList.add(linearLayout89);
        linearLayoutList.add(linearLayout90);
        linearLayoutList.add(linearLayout91);
        linearLayoutList.add(linearLayout92);
        linearLayoutList.add(linearLayout93);
        linearLayoutList.add(linearLayout94);
        linearLayoutList.add(linearLayout95);
        linearLayoutList.add(linearLayout96);
        linearLayoutList.add(linearLayout97);
        linearLayoutList.add(linearLayout98);
        linearLayoutList.add(linearLayout99);
        linearLayoutList.add(linearLayout100);
        linearLayoutList.add(linearLayout101);
        linearLayoutList.add(linearLayout102);
        linearLayoutList.add(linearLayout103);
        linearLayoutList.add(linearLayout104);
        linearLayoutList.add(linearLayout105);
        linearLayoutList.add(linearLayout106);
        linearLayoutList.add(linearLayout107);
        linearLayoutList.add(linearLayout108);
        linearLayoutList.add(linearLayout109);
        linearLayoutList.add(linearLayout110);
        linearLayoutList.add(linearLayout111);
        linearLayoutList.add(linearLayout112);
        linearLayoutList.add(linearLayout113);
        linearLayoutList.add(linearLayout114);
        linearLayoutList.add(linearLayout115);
        linearLayoutList.add(linearLayout116);
        linearLayoutList.add(linearLayout117);
        linearLayoutList.add(linearLayout118);

        View.OnClickListener onClickListener = new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if (toast!=null) {
                    toast.cancel();
                }
                String tag = v.getTag().toString();
                int num = Integer.parseInt(tag);

                Intent intent = new Intent(getActivity(), ElementInfoActivity.class);
                intent.putExtra("elementNum", num);
                startActivity(intent);

//                Element element = DatabaseAccess.getInstance(getContext()).getElementFromTable(tag);
//                toast = Toast.makeText(getContext(), "element " + element.getRuTitle() + "\nweight " + element.getWeight(), Toast.LENGTH_SHORT);
//                toast.show();
            }
        };
        for (LinearLayout layout: linearLayoutList){
            layout.setOnClickListener(onClickListener);
        }
        return root;
    }



    @Override
    public void onActivityCreated(@Nullable Bundle savedInstanceState) {
        super.onActivityCreated(savedInstanceState);
        mViewModel = ViewModelProviders.of(this).get(LongTableViewModel.class);
        // TODO: Use the ViewModel
    }


}
